### PR TITLE
Support for HTCondor clusters

### PR DESCRIPTION
**Pull request by Martin1887**
Add a `HTCondorEnvironment` to launch experiments in a HTCondor cluster.

### CODE REVIEW

**Comment by jendrikseipp** [comment]
Thanks for the PR. I don't think integrating support for HTCondor clusters into Lab is the best solution here, though. We have no way of testing HTCondor support, so maintaining the code is difficult. Luckily, it seems that you can simply add the recommended code to your projects which need it. Apart from the reordering of methods in lab/experiment.py, your changes don't require any alterations of the main Lab code base.

If you can explain why the reordering is needed and reduce the PR to just that change, I'm happy to merge it.

**Comment by Martin1887** [comment]
Hi, Jendrik.

I understand that you don't want to include a configuration that you cannot test in the main repository. However, I think that this feature can potentially help many users, so I think the best approach is writing the `HTCondorEnvironment` class in a standalone Python module and including this module in a community extensions repository. This community extensions repository should be advertised in the main documentation to allow users to find it.

Respect the reordering of method calls in `experiment.py`, it is necessary because the main script could need some files created in the previous steps. For instance, the `HTCondor` environment reads the `run` script and patches the paths because all files are in the same directory in the cluster node.

**Comment by Martin1887** [comment]
Any question or update about this?

Thanks.

**Comment by jendrikseipp** [comment]
Sounds good. Let's keep your change to `lab/experiment.py` and move the HTCondorEnvironment class somewhere we can link to from the Lab documentation. Do you have a public GitHub repo that we can link to? I suggest adding the link to https://lab.readthedocs.io/en/stable/lab.experiment.html#environment, i.e., explain that Lab supports two environments out of the box, but that HTCondor support can be found when following the link.

**Comment by Martin1887** [comment]
Perfect, I will create an independent repository with the `HTCondorEnvironment` class and a `README.md` explaining how it works and some particularities.

When it is ready I will edit the documentation and remove the `HTCondorEnvironment` class from this pull request.

Thanks.

**Comment by Martin1887** [comment]
Hi, the code has already been migrated to a external repository and the documentation modified.

Feel free to edit the documentation text.

Thanks.

**Comment by jendrikseipp** [comment]
Thanks!

**Pull request merged**
