### PR TITLE
Update cached_revision.py

### PR DESCRIPTION
**Pull request by FlorianPommerening**
experiments and misc are now ignored by `.gitattributes` and will not show up in the archive

### CODE REVIEW

**Comment by jendrikseipp** [comment]
FWIW, you can fix the style with "tox -e fix-style".

**Comment by FlorianPommerening** [comment]
I did this purely on GitHub, so I don't have a local clone where I can run this. I tried to guess what the problem is and fix it. If that doesn't work, I'll clone. For cases like this it would be nice if the style checks also reported the problem and not just that there is a problem.

**Comment by jendrikseipp** [comment]
I agree. I'll see if this can be fixed.

**Comment by jendrikseipp** [comment]
Thinking about this again, I don't think we should make this change now since this makes the Mercurial caches much bigger. I'll add a comment to the code to revisit this later.

**Comment by jendrikseipp** [comment]
BTW, there are now diffs for style issues :-)

**Comment by FlorianPommerening** [comment]
Sounds good.

**Pull request closed without merging**
